### ISSUE TITLE
object file suffix is assumed to be .s19

### ISSUE THREAD

**Issue by ricknun** [dsherman26/ET3400A#1]
(Re-typed because STAR is interpreted as italics or other formatting.) I am using v1.5 on a Windows 10 PC. File, Load pops up a File Manager window with "File name: STAR.s19" and "Files of type: All Files (STAR.STAR)". My assembler creates .obj files with no option to change that suffix. Clicking on the "All Files (STAR.STAR)" menu does not change the "STAR.s19" to "STAR.STAR". Clicking "STAR.s19" and typing "STAR.STAR <Enter>" allows me to see and load my .obj files, but it gets old quick when developing a program and doing that again and again. Better I think would be to default to "STAR.STAR" and let the user type "STAR.s19" or "STAR.obj" or whatever if they have many files in the directory.

**Comment by dsherman26** [comment]
Default filename filter in the file dialogs now defaults to "*.*".
