### ISSUE TITLE
default speed is way too fast

### ISSUE THREAD

**Issue by ricknun** [dsherman26/ET3400A#2]
Using v1.5 on a Windows 10 PC with Intel Core i7-10700 2.9 GHz CPU. The default speed slider is at about 90% full scale and so fast display updates can't be seen. Even at 0% (full left) the speed is still faster than my real ET-3400, but at least usable for my purposes. Suggestion: A logarithmic slider (e.g. 10% change multiplies or divides by X), from "OK on a modern PC of your choice" in the middle to many factors faster or slower at the extremes.

**Comment by ricknun** [comment]
https://groups.io/g/ET-3400/topic/90918910 explains why ET-3400 sample program number 1 should take 11.0 seconds to repeat. That is a good goal for default execution speed.

**Comment by dsherman26** [comment]
Hi Rick, I haven't forgotten about you.  I'm hoping to get back to it soon.  I've never liked that Java doesn't have a means to create short delays, so I'm not surprised it depends heavily on the host CPU speed.  I should be able to give it more adjustment to make it considerably slower.

**Comment by ricknun** [comment]
I've never tried this, but Java System.nanoTime() allows **measuring** both execution and delay times. A looping program (like interpreting each MC6800 opcode) could track ideal runtime so far (knowing 6800 CPU cycles per opcode) and total runtime so far. Then every opcode execute: X = ideal runtime - actual runtime; if X >= 1 ms then sleep(X ms). In the case of waiting for an interrupt (WAI) the accumulation of ideal and actual runtime both stop until opcode processing starts up again. This would make **the average runtime** be correct, with very frequent correction.

**Comment by ricknun** [comment]
This relates to the "feature request: load alternate ROM image" issue too -- See
https://groups.io/g/ET-3400/topic/what_to_do_with_34_bytes_of/91005201
for a ROM image with built-in timing metric for emulators. DO FFD6 runs the Heathkit Sample 1 demo program that ideally takes 11.0 seconds to repeat.

**Comment by dsherman26** [comment]
The default speed will allow the display test program to complete in approximately 11 seconds, tested on a Core i7 2.6 GHz.  The speed adjustment also has better control now and defaults to the middle of the range.
