### ISSUE TITLE
display hardware not properly decoded

### ISSUE THREAD

**Issue by ricknun** [dsherman26/ET3400A#4]
The ET-3400 manual, page 87, "Memory Decoding", "DISPLAY" shows address $C1GS (diGit nibble, Segment nibble) controls the 6 7-segment displays with address bits 3 and 7 "don't care". That means an emulator must decode either 0 or 1 on either of those addresses as addressing the LED. This emulator doesn't do that, as shown in the attached display_test.lst(.txt for GitHub) and display_tst.s19(.txt for GitHub) files. When run on real ET-3400 hardware the program always shows a single segment lit (with no all-blank display ever) as it writes to each possible address. More details are in the listing file.
[display_test.txt](https://github.com/dsherman26/ET3400A/files/8654632/display_test.txt)
[display_tst.txt](https://github.com/dsherman26/ET3400A/files/8654634/display_tst.txt)

Edit after initial post: Error in display_test.asm(.txt) -- Change "digit 000 (right) to 110 (left)" to "digit 001 (right) to 110 (left)".

**Comment by dsherman26** [comment]
Thanks Rick, I didn't know the display test program purposely writes to the alternate addresses with the "don't care" bits.  Should be easy to implement though.

**Comment by ricknun** [comment]
This issue was found in another program I was writing that did direct hardware writes to $C1xx that I couldn't get working (on emulators) and finally reduced it to the display_test program. It wasn't until I manually entered it on real ET-3400 hardware that I found my problem. That program is just to demonstrate the problem. The issue in in all 3 ET-3400 emulators I use and I filed it in 3 locations on GitHub.

**Comment by ricknun** [comment]
In an extreme coincidence, last night (the day after filing this issue) while looking for some unrelated 6800 information I stumbled on this web page.
http://www.science.smith.edu/~jfrankli/270s02/labs/lab11.htm
The "Mystery Program" at the bottom of the page results in a blank display on the v1.5 emulator because it writes to display addresses "C1 68 ... C1 58 ... C1 48 ... C1 38 ... C1 28". It counts on the "don't care" display segment address bit being a 1 (the MS bit of the "8" values). Changing those "8" nibbles to "0" makes the program work on the emulator, but that shouldn't be required.

**Comment by dsherman26** [comment]
The "don't care" address bits in the display addresses are treated accordingly, so the display decodes appropriately.
