### ISSUE TITLE
feature request: load alternate ROM image

### ISSUE THREAD

**Issue by ricknun** [dsherman26/ET3400A#5]
I am building a new ET-3400 ROM image and the only emulator I know of that allows trying it out is the older Santos C# emulator at https://github.com/RupertAvery/et3400-emu.  It has a "File, Load ROM" menu selection that would be a welcome addition to this project.

**Comment by dsherman26** [comment]
Hi Rick, so it should be similar to loading the user program, but loading it into the ROM instead?  Should be pretty simple, but just so I'm certain, should it just assume the S-record you're loading will begin at FC00 and be exactly 1KB in size?  Wasn't sure if there was a possibility that it might need to start loading at a different location according to the S-record.  For that matter, the emulator isn't limited by the physical size of the ROM or the address bits, so it could easily be expanded to allow 8K of ROM without overlapping the display or keypad.  That would require learning the ROM starting address from the S-record, however.

**Comment by ricknun** [comment]
What I have (not sure what others might want) is the attached two file formats, both .txt for GitHub. One is Motorola S-Record and one is what the Santos C# emulator requires -- just the data bytes in ASCII with no address information. These are for the original ET-3400 ROM image.

[ROM_s19.txt](https://github.com/dsherman26/ET3400A/files/8656294/ROM_s19.txt)
[ROM_hex.txt](https://github.com/dsherman26/ET3400A/files/8656295/ROM_hex.txt)

**Comment by dsherman26** [comment]
Thanks Rick, files like those would work.  I was looking at the ROM images on groups.io, and remembered that those are targeting a 2716 (2 KB).  They have a 1KB offset built in, so what starts at 0x400 in those S-records is actually at 0xFC00.  For now, it's going to assume there's no padding or offset and will start loading from the beginning of the file.  Sound like a plan?

**Comment by ricknun** [comment]
All the ET-3400 (not A or other later models) ROM images that I know about are 1 KB, for the 1 KB part on the board that says "ROM (FC00)" next to it. ROM_s19.txt starts "S11BFC00" and the FC00 is the start address of the 1 KB of data that follows.

**Comment by dsherman26** [comment]
It is now possible to load a new ROM image.  First S-record will be loaded starting from 0xFC00 regardless of S-record address.
